### ISSUE TITLE
Catching network outages during fetch

### ISSUE THREAD

**Issue by andywilsonuk** [samundrak/fetch-progress#1]
Hello,

I've been tested what happens if there is a network outage during a fetch (using Chrome DevTools), it seems that in the current implementation the reader.read() doesn't have a catch block nor does it return a promise so that it can be caught further up the chain. I was thinking that passing in a onError function might provide a solution to this, what do you think?

Thanks
Andy

**Comment by samundrak** [comment]
Hi @andywilsonuk ,
Thanks for the suggestion.
Would you like to submit PR for this issue?

**Comment by andywilsonuk** [comment]
Yep will do.
